CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    job_url VARCHAR(2048),
    description TEXT,
    source VARCHAR(100),
    external_job_id VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'DISCOVERED',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT jobs_status_check CHECK (status IN
        ('DISCOVERED', 'SHORTLISTED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN'))
);
