CREATE TABLE resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    media_type VARCHAR(100) NOT NULL,
    extracted_text TEXT NOT NULL,
    page_count INTEGER NOT NULL CHECK (page_count > 0),
    extractor_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE candidate_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL UNIQUE REFERENCES resumes(id) ON DELETE CASCADE,
    profile_data JSONB NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    vocabulary_version VARCHAR(32) NOT NULL,
    assessed_on DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

