CREATE TABLE job_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(32) NOT NULL,
    region VARCHAR(16) NOT NULL,
    source_key VARCHAR(100) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    last_successful_sync_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT job_sources_provider_check CHECK (provider IN ('LEVER')),
    CONSTRAINT job_sources_region_check CHECK (region IN ('GLOBAL', 'EU')),
    CONSTRAINT job_sources_source_key_not_blank CHECK (btrim(source_key) <> ''),
    CONSTRAINT job_sources_source_key_canonical_check CHECK (source_key = lower(btrim(source_key))),
    CONSTRAINT job_sources_source_key_control_free_check CHECK (source_key !~ '[[:cntrl:]]'),
    CONSTRAINT job_sources_company_name_not_blank CHECK (btrim(company_name) <> ''),
    CONSTRAINT job_sources_last_sync_not_before_creation_check
        CHECK (last_successful_sync_at IS NULL OR last_successful_sync_at >= created_at),
    CONSTRAINT uq_job_sources_identity UNIQUE (provider, region, source_key)
);

CREATE TABLE external_job_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_source_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    external_job_id VARCHAR(255) NOT NULL,
    availability VARCHAR(16) NOT NULL,
    provider_content_digest VARCHAR(128) NOT NULL,
    hosted_job_url VARCHAR(2048),
    apply_url VARCHAR(2048),
    first_seen_at TIMESTAMP(6) NOT NULL,
    last_seen_at TIMESTAMP(6) NOT NULL,
    last_verified_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_external_job_listings_source FOREIGN KEY (job_source_id)
        REFERENCES job_sources(id) ON DELETE RESTRICT,
    CONSTRAINT fk_external_job_listings_job FOREIGN KEY (job_id)
        REFERENCES jobs(id) ON DELETE CASCADE,
    CONSTRAINT external_job_listings_external_id_not_blank CHECK (btrim(external_job_id) <> ''),
    CONSTRAINT external_job_listings_external_id_canonical_check CHECK (external_job_id = btrim(external_job_id)),
    CONSTRAINT external_job_listings_external_id_control_free_check CHECK (external_job_id !~ '[[:cntrl:]]'),
    CONSTRAINT external_job_listings_digest_not_blank CHECK (btrim(provider_content_digest) <> ''),
    CONSTRAINT external_job_listings_availability_check CHECK (availability IN ('LIVE', 'CLOSED')),
    CONSTRAINT external_job_listings_seen_order_check
        CHECK (first_seen_at <= last_seen_at AND last_seen_at <= last_verified_at),
    CONSTRAINT uq_external_job_listings_source_external_id UNIQUE (job_source_id, external_job_id),
    CONSTRAINT uq_external_job_listings_job UNIQUE (job_id)
);

CREATE INDEX ix_external_job_listings_source_availability
    ON external_job_listings (job_source_id, availability);

CREATE TABLE job_source_sync_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_source_id BIGINT NOT NULL,
    trigger VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    failure_code VARCHAR(64),
    started_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    discovered_count INTEGER NOT NULL DEFAULT 0,
    created_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    unchanged_count INTEGER NOT NULL DEFAULT 0,
    closed_count INTEGER NOT NULL DEFAULT 0,
    reopened_count INTEGER NOT NULL DEFAULT 0,
    ranking_ready_count INTEGER NOT NULL DEFAULT 0,
    unready_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_job_source_sync_runs_source FOREIGN KEY (job_source_id)
        REFERENCES job_sources(id) ON DELETE RESTRICT,
    CONSTRAINT job_source_sync_runs_trigger_check CHECK (trigger IN ('MANUAL', 'SCHEDULED')),
    CONSTRAINT job_source_sync_runs_status_check CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'ABANDONED')),
    CONSTRAINT job_source_sync_runs_failure_code_check CHECK (
        failure_code IS NULL OR failure_code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    CONSTRAINT job_source_sync_runs_terminal_state_check CHECK (
        (status = 'RUNNING' AND completed_at IS NULL AND failure_code IS NULL)
        OR (status = 'SUCCEEDED' AND completed_at IS NOT NULL AND failure_code IS NULL)
        OR (status IN ('FAILED', 'ABANDONED') AND completed_at IS NOT NULL AND failure_code IS NOT NULL)
    ),
    CONSTRAINT job_source_sync_runs_time_order_check
        CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT job_source_sync_runs_nonnegative_counts_check CHECK (
        discovered_count >= 0 AND created_count >= 0 AND updated_count >= 0
        AND unchanged_count >= 0 AND closed_count >= 0 AND reopened_count >= 0
        AND ranking_ready_count >= 0 AND unready_count >= 0
    )
);

CREATE INDEX ix_job_source_sync_runs_source_started
    ON job_source_sync_runs (job_source_id, started_at DESC);

CREATE UNIQUE INDEX ux_job_source_sync_runs_one_running_per_source
    ON job_source_sync_runs (job_source_id)
    WHERE status = 'RUNNING';
