ALTER TABLE candidate_profiles
    ALTER COLUMN resume_id DROP NOT NULL,
    ADD COLUMN full_name VARCHAR(255),
    ADD COLUMN email VARCHAR(320),
    ADD COLUMN phone VARCHAR(64),
    ADD COLUMN location VARCHAR(255),
    ADD COLUMN current_title VARCHAR(255),
    ADD COLUMN total_relevant_experience_months INTEGER,
    ADD COLUMN work_authorization VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN sponsorship_required VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN relocation_willing VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN notice_period_days INTEGER,
    ADD COLUMN compensation_currency VARCHAR(3),
    ADD COLUMN minimum_compensation NUMERIC(14,2),
    ADD COLUMN desired_compensation NUMERIC(14,2),
    ADD COLUMN updated_at TIMESTAMP(6);

UPDATE candidate_profiles SET updated_at = created_at WHERE updated_at IS NULL;
ALTER TABLE candidate_profiles ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE candidate_profiles
    ADD CONSTRAINT candidate_profiles_work_authorization_check
        CHECK (work_authorization IN ('YES', 'NO', 'UNKNOWN')),
    ADD CONSTRAINT candidate_profiles_sponsorship_check
        CHECK (sponsorship_required IN ('YES', 'NO', 'UNKNOWN')),
    ADD CONSTRAINT candidate_profiles_relocation_check
        CHECK (relocation_willing IN ('YES', 'NO', 'UNKNOWN')),
    ADD CONSTRAINT candidate_profiles_experience_check
        CHECK (total_relevant_experience_months IS NULL OR total_relevant_experience_months BETWEEN 0 AND 960),
    ADD CONSTRAINT candidate_profiles_notice_check
        CHECK (notice_period_days IS NULL OR notice_period_days BETWEEN 0 AND 730),
    ADD CONSTRAINT candidate_profiles_text_check CHECK (
        (full_name IS NULL OR (full_name = btrim(full_name) AND full_name <> '' AND full_name !~ '[[:cntrl:]]'))
        AND (email IS NULL OR (email = btrim(email) AND email ~ '^[^[:space:]@]+@[^[:space:]@]+$'
            AND email !~ '[[:cntrl:]]'))
        AND (phone IS NULL OR (phone = btrim(phone) AND phone <> '' AND phone !~ '[[:cntrl:]]'))
        AND (location IS NULL OR (location = btrim(location) AND location <> '' AND location !~ '[[:cntrl:]]'))
        AND (current_title IS NULL OR (current_title = btrim(current_title) AND current_title <> '' AND current_title !~ '[[:cntrl:]]'))),
    ADD CONSTRAINT candidate_profiles_compensation_check CHECK (
        (minimum_compensation IS NULL AND desired_compensation IS NULL AND compensation_currency IS NULL)
        OR (compensation_currency IS NOT NULL
            AND (minimum_compensation IS NOT NULL OR desired_compensation IS NOT NULL)
            AND compensation_currency ~ '^[A-Z]{3}$'
            AND (minimum_compensation IS NULL OR minimum_compensation >= 0)
            AND (desired_compensation IS NULL OR desired_compensation >= 0)
            AND (minimum_compensation IS NULL OR desired_compensation IS NULL
                 OR desired_compensation >= minimum_compensation))
    );

CREATE TABLE job_search_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL UNIQUE REFERENCES candidate_profiles(id) ON DELETE CASCADE,
    default_resume_strategy VARCHAR(16) NOT NULL,
    minimum_experience_tolerance_years NUMERIC(4,2),
    maximum_experience_tolerance_years NUMERIC(4,2),
    freshness_days INTEGER,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT job_search_preferences_strategy_check CHECK (default_resume_strategy IN ('VOLUME', 'PRECISION')),
    CONSTRAINT job_search_preferences_min_tolerance_check CHECK (
        minimum_experience_tolerance_years IS NULL OR minimum_experience_tolerance_years BETWEEN 0 AND 80),
    CONSTRAINT job_search_preferences_max_tolerance_check CHECK (
        maximum_experience_tolerance_years IS NULL OR maximum_experience_tolerance_years BETWEEN 0 AND 80),
    CONSTRAINT job_search_preferences_tolerance_order_check CHECK (
        minimum_experience_tolerance_years IS NULL OR maximum_experience_tolerance_years IS NULL
        OR minimum_experience_tolerance_years <= maximum_experience_tolerance_years),
    CONSTRAINT job_search_preferences_freshness_check CHECK (freshness_days IS NULL OR freshness_days BETWEEN 1 AND 365)
);

CREATE TABLE job_search_preference_roles (
    preference_id BIGINT NOT NULL REFERENCES job_search_preferences(id) ON DELETE CASCADE,
    kind VARCHAR(16) NOT NULL,
    role_title VARCHAR(255) NOT NULL,
    PRIMARY KEY (preference_id, kind, role_title),
    CONSTRAINT job_search_preference_roles_kind_check CHECK (kind IN ('TARGET', 'EXCLUDED')),
    CONSTRAINT job_search_preference_roles_title_check CHECK (
        role_title = btrim(role_title) AND role_title <> '' AND role_title !~ '[[:cntrl:]]')
);

CREATE TABLE job_search_preference_locations (
    preference_id BIGINT NOT NULL REFERENCES job_search_preferences(id) ON DELETE CASCADE,
    location VARCHAR(255) NOT NULL,
    PRIMARY KEY (preference_id, location),
    CONSTRAINT job_search_preference_locations_value_check CHECK (
        location = btrim(location) AND location <> '' AND location !~ '[[:cntrl:]]')
);

CREATE UNIQUE INDEX ux_job_search_preference_roles_canonical
    ON job_search_preference_roles(preference_id, lower(role_title));
CREATE UNIQUE INDEX ux_job_search_preference_locations_canonical
    ON job_search_preference_locations(preference_id, lower(location));

CREATE TABLE job_search_preference_work_arrangements (
    preference_id BIGINT NOT NULL REFERENCES job_search_preferences(id) ON DELETE CASCADE,
    arrangement VARCHAR(16) NOT NULL,
    PRIMARY KEY (preference_id, arrangement),
    CONSTRAINT job_search_preference_work_arrangements_check CHECK (arrangement IN ('REMOTE', 'HYBRID', 'ONSITE'))
);

CREATE TABLE resume_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(id) ON DELETE CASCADE,
    resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE RESTRICT,
    strategy VARCHAR(16) NOT NULL,
    role_family VARCHAR(255),
    is_default BOOLEAN NOT NULL,
    variant_label VARCHAR(255) NOT NULL,
    approved BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT resume_routes_strategy_check CHECK (strategy IN ('VOLUME', 'PRECISION')),
    CONSTRAINT resume_routes_role_family_check CHECK (
        (is_default AND role_family IS NULL)
        OR (NOT is_default AND role_family IS NOT NULL AND role_family = btrim(role_family)
            AND role_family <> '' AND role_family !~ '[[:cntrl:]]')),
    CONSTRAINT resume_routes_variant_label_check CHECK (
        variant_label = btrim(variant_label) AND variant_label <> '' AND variant_label !~ '[[:cntrl:]]')
);

CREATE UNIQUE INDEX ux_resume_routes_default
    ON resume_routes(candidate_profile_id, strategy) WHERE is_default AND approved;
CREATE UNIQUE INDEX ux_resume_routes_role_family
    ON resume_routes(candidate_profile_id, strategy, lower(role_family)) WHERE NOT is_default AND approved;
